/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.devwhyqueue.odsgradegetter.tordownloader;


import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

import de.devwhyqueue.odsgradegetter.tordownloader.model.Credentials;
import de.devwhyqueue.odsgradegetter.tordownloader.model.TranscriptOfRecords;
import de.devwhyqueue.odsgradegetter.tordownloader.session.SessionException;
import de.devwhyqueue.odsgradegetter.tordownloader.session.SessionHandler;
import de.devwhyqueue.odsgradegetter.tordownloader.webscraping.TranscriptOfRecordsWebScraper;
import de.devwhyqueue.odsgradegetter.tordownloader.webscraping.TranscriptOfRecordsWebScraperException;

public class TranscriptOfRecordsDownloader {
    private final Credentials credentials;

    public TranscriptOfRecordsDownloader(Credentials credentials) {
        this.credentials = credentials;
    }

    public CompletableFuture<TranscriptOfRecords> start() {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return download();
            } catch (SessionException | TranscriptOfRecordsWebScraperException e) {
                throw new CompletionException(e);
            }
        });
    }

    private TranscriptOfRecords download() throws SessionException, TranscriptOfRecordsWebScraperException {
        try (SessionHandler sessionHandler = new SessionHandler()) {
            String sidd = sessionHandler.open(this.credentials);
            TranscriptOfRecordsWebScraper torScraper = new TranscriptOfRecordsWebScraper();
            return torScraper.getTranscriptOfRecords(sidd);
        }
    }
}
